name: ServerSection
version: '${project.version}'
main: org.yashar.serversection.ServerSection
api-version: '1.20'
commands:
  lobbyselector:
    description: Opens the lobby selector menu.
    usage: /lobbyselector
