lobbies:
  lobby1:
    name: "&aLobby 1"  # نام لابی
    material: "DIAMOND"  # متریالی که در GUI نمایش داده می‌شود

  lobby2:
    name: "&bLobby 2"  # نام لابی
    material: "EMERALD"  # متریالی که در GUI نمایش داده می‌شود

  lobby3:
    name: "&cLobby 3"  # نام لابی
    material: "GOLD_INGOT"  # متریالی که در GUI نمایش داده می‌شود
